export type Challenge = {
  id: number
  word: string
  tip: string
}

export const WORDS: Challenge[] = [
  { id: 1, word: "CSS", tip: "Linguagem de estilos" },
  { id: 2, word: "REACT", tip: "Biblioteca para criar interfaces Web" },
  { id: 3, word: "HTML", tip: "Linguagem de marcação" },
  {
    id: 4,
    word: "JavaScript",
    tip: "Uma das linguagens mais utilizadas no mundo",
  },
  { id: 5, word: "TypeScript", tip: "Para adicionar tipagem no JavaScript" },
  { id: 6, word: "abacaxi", tip: "Fruta tropical com casca espinhosa" },
  { id: 7, word: "amizade", tip: "Relação de afeto entre pessoas" },
  { id: 8, word: "astronauta", tip: "Profissional que viaja ao espaço" },
  { id: 9, word: "bicicleta", tip: "Meio de transporte com pedais" },
  { id: 10, word: "borboleta", tip: "Inseto com asas coloridas" },
  { id: 11, word: "cachoeira", tip: "Queda d'água natural" },
  { id: 12, word: "camaleão", tip: "Réptil que muda de cor" },
  { id: 13, word: "caneta", tip: "Objeto usado para escrever" },
  { id: 14, word: "castelo", tip: "Construção fortificada de grande porte" },
  { id: 15, word: "cavalete", tip: "Estrutura usada para suporte" },
  { id: 16, word: "cenoura", tip: "Vegetal alaranjado comestível" },
  { id: 17, word: "deserto", tip: "Região árida com pouca chuva" },
  { id: 18, word: "diamante", tip: "Pedra preciosa muito valiosa" },
  { id: 19, word: "escorregador", tip: "Brinquedo de parque infantil" },
  { id: 20, word: "esmeralda", tip: "Pedra preciosa de cor verde" },
  { id: 21, word: "estetoscópio", tip: "Equipamento usado por médicos" },
  { id: 22, word: "foguete", tip: "Veículo que viaja ao espaço" },
  { id: 23, word: "girassol", tip: "Flor que segue o sol" },
  { id: 24, word: "golfinho", tip: "Animal marinho inteligente" },
  { id: 25, word: "guitarra", tip: "Instrumento musical com cordas" },
  { id: 26, word: "helicóptero", tip: "Veículo aéreo com hélices" },
  { id: 27, word: "horizonte", tip: "Linha onde o céu encontra a terra" },
  { id: 28, word: "iguana", tip: "Réptil comum em regiões tropicais" },
  { id: 29, word: "jabuticaba", tip: "Fruta pequena e preta" },
  { id: 30, word: "jangada", tip: "Embarcação feita de madeira" },
  { id: 31, word: "kiwi", tip: "Fruta de casca peluda e polpa verde" },
  { id: 32, word: "lanterna", tip: "Objeto usado para iluminar" },
  { id: 33, word: "limonada", tip: "Bebida feita com limão" },
  { id: 34, word: "lápis", tip: "Instrumento usado para escrever" },
  { id: 35, word: "lã", tip: "Material obtido da ovelha" },
  { id: 36, word: "macaco", tip: "Animal que vive em árvores" },
  { id: 37, word: "mangueira", tip: "Árvore que dá mangas" },
  { id: 38, word: "maratona", tip: "Corrida de longa distância" },
  { id: 39, word: "montanha", tip: "Grande elevação natural do terreno" },
  { id: 40, word: "navio", tip: "Embarcação de grande porte" },
  { id: 41, word: "nó", tip: "Laço em uma corda" },
  { id: 42, word: "oceano", tip: "Grande corpo de água salgada" },
  { id: 43, word: "orquestra", tip: "Grupo de músicos que tocam juntos" },
  { id: 44, word: "pinguim", tip: "Ave que vive em regiões frias" },
  { id: 45, word: "pipoca", tip: "Alimento feito com milho" },
  { id: 46, word: "planeta", tip: "Corpo celeste que orbita uma estrela" },
  { id: 47, word: "praia", tip: "Região de encontro entre mar e terra" },
  { id: 48, word: "quadrado", tip: "Forma geométrica com quatro lados iguais" },
  { id: 49, word: "quebra-cabeça", tip: "Jogo de encaixar peças" },
  { id: 50, word: "quintal", tip: "Espaço externo de uma casa" },
  { id: 51, word: "raio", tip: "Fenômeno elétrico durante tempestades" },
  { id: 52, word: "rapadura", tip: "Doce feito de cana-de-açúcar" },
  { id: 53, word: "relógio", tip: "Instrumento que marca o tempo" },
  { id: 54, word: "rio", tip: "Curso natural de água" },
  { id: 55, word: "safira", tip: "Pedra preciosa de cor azul" },
  {
    id: 56,
    word: "sanduíche",
    tip: "Alimento com recheio entre fatias de pão",
  },
  { id: 57, word: "satélite", tip: "Objeto que orbita um planeta" },
  { id: 58, word: "selva", tip: "Floresta densa e tropical" },
  { id: 59, word: "sino", tip: "Objeto que emite som quando tocado" },
  { id: 60, word: "sol", tip: "Estrela que ilumina a Terra" },
  { id: 61, word: "tartaruga", tip: "Animal com casco" },
  { id: 62, word: "tatu", tip: "Animal com carapaça" },
  { id: 63, word: "teclado", tip: "Acessório usado para digitar" },
  { id: 64, word: "telefone", tip: "Aparelho para comunicação à distância" },
  { id: 65, word: "telescópio", tip: "Instrumento para observar astros" },
  { id: 66, word: "tesoura", tip: "Ferramenta para cortar" },
  { id: 67, word: "tigre", tip: "Felino de grande porte com listras" },
  { id: 68, word: "torneira", tip: "Dispositivo para liberar água" },
  { id: 69, word: "trator", tip: "Veículo usado na agricultura" },
  { id: 70, word: "uva", tip: "Fruta pequena usada para fazer vinho" },
  { id: 71, word: "vaca", tip: "Animal" },
]
